#!/usr/bin/ruby

require 'lib/omniture'
require 'date'
require 'trollop'

# ----

args = Trollop::options do
    opt :byline, "Byline", :type => :string        # string --name <s>, default nil
    opt :from, "From (days)", :type => :int        # string --name <s>, default nil
end

# ------

yesterday = (Date.today - 1).strftime('%Y-%m-%d') 

puts Report.new().queueTrended(
                                {
                                  :from => (Date.today - args[:from]).strftime('%Y-%m-%d'),
                                  :to => yesterday,
                                  :evars => [args[:byline]],
                                  :metric => "pageViews",
                                  :element_id => "prop6"
                                }
                              )
        
