#!/usr/bin/ruby

require 'lib/omniture'
require 'date'
require 'trollop'

def days_from_today(n)
    (Date.today - n).strftime('%Y-%m-%d') 
end

args = Trollop::options do
    opt :data, "data link names", :type => :string
    opt :from,   "From (days)", :type => :int, :default => 30 
    opt :to,     "To (days)",   :type => :int, :default => 1
end

report = Report.new().queueTrended(
                {
                  :from => days_from_today(args[:from]),
                  :to => days_from_today(args[:to]),
                  :segment => "",
                  :metric => "event37",
                  :element_id => "evar37",
                  :evars => args[:data].split(",")
                })

puts report

