#!/usr/bin/ruby

require 'lib/omniture'
require 'date'

yesterday = (Date.today-1).strftime('%Y-%m-%d') 

opts = {
         :date => yesterday,
         :metrics => ['pageViews', 'visits', 'visitors', 'averageTimeSpentOnSite', 'averageVisitDepth', 'visitorsNew']
       }

puts Report.new().queueQueueOvertime(opts)
